fix repo
mendix/nanoflow-commons pull request #1
Opened 2022-11-28 08:28 UTC by UrazAkgultan

2022-12-05 11:39 UTC, iobuhov requested changes

2022-12-05 11:39 UTC, iobuhov commented on .github/workflows/Build.yml
> +        run: echo "::set-output name=arg::$(if [ "${{ steps.files.outputs.global_files }}" = "" ] && ${{ github.event_name == 'pull_request' }}; then echo '--since'; else echo ''; fi)"
`set-output` expression is deprecated, I would switch to new syntax 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

2022-12-05 11:39 UTC, iobuhov commented on .github/workflows/MarketplaceRelease.yml
> +        run: echo "::set-output name=tag::$(git tag --points-at HEAD)"
Same as above, let update `set-output`

2022-12-05 11:39 UTC, iobuhov commented on .github/workflows/PullRequestLabeler.yml
> +          repo-token: ${{ secrets.GH_PAT }}
not a big deal, but you can use `${{ github.token }}` to not rely on secrets

2022-12-05 11:39 UTC, iobuhov commented on .github/workflows/Release.yml
> +        run: echo "::set-output name=arg::$(if [ "${{ steps.files.outputs.global_files }}" = "" ] && ${{ github.event_name == 'pull_request' }}; then echo '--since'; else echo ''; fi)"
Same here, let's get rid of `set-output`

2022-12-14 09:37 UTC, iobuhov requested changes
One last step

2022-12-14 09:37 UTC, iobuhov commented on .github/workflows/Build.yml
> +        run: echo "arg=$(If ('${{ steps.files.outputs.global_files }}' -eq '' -AND '${{ github.event_name == 'pull_request' }}' -eq 'true'){ echo '--since' } Else { echo '' })" >> $GITHUB_OUTPUT
On windows you have to use `$env:GITHUB_OUTPUT`
https://docs.github.com/en/actions/learn-github-actions/environment-variables#detecting-the-operating-system

2022-12-14 09:37 UTC, iobuhov commented on .github/workflows/Build.yml
> +        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
Same here, this will be incorrect on windows, so I recommentd
```
>> ${{ runner.os == 'Windows' && '$env:GITHUB_ENV' || '$GITHUB_ENV' }}
```

2022-12-14 09:37 UTC, iobuhov commented on .github/workflows/Release.yml
> +        run: echo "arg=$(If ('${{ steps.files.outputs.global_files }}' -eq '' -AND '${{ github.event_name == 'pull_request' }}' -eq 'true'){ echo '--since' } Else { echo '' })" >> $GITHUB_OUTPUT
Same required here, to prevent fail on windows use `$env:GITHUB_OUTPUT`

2022-12-14 09:37 UTC, iobuhov commented on .github/workflows/Release.yml
> +        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
```
>> ${{ runner.os == 'Windows' && '$env:GITHUB_ENV' || '$GITHUB_ENV' }}
```

2022-12-14 12:26 UTC, iobuhov approved these changes

2022-12-19 10:19 UTC, diego-antonelli approved these changes

2022-12-20 10:02 UTC, merged